### ISSUE TITLE
Possible duplicate content (SEO)

### ISSUE THREAD

**Issue by jslirola** [shimizust/trackyourclimb#1]
Hello, I saw that your domain don't do a redirection when I load it with or without "www". Could be an inconvenience to SEO. If you want to change it, you can add this lines to your `.htaccess`

```
RewriteCond %{HTTP_HOST} ^yourdomain.com [NC]
RewriteRule ^(.*)$ http://www.yourdomain.com/$1 [L,R=301]
```

Regards

**Comment by shimizust-zz** [comment]
Hi jslirola,

Thanks for noticing that. I've fixed the .htaccess to redirect from www to non-www.

Cheers
